# Generated by Django 5.2.7 on 2025-11-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('case_study_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_study_user', models.CharField(blank=True, max_length=100, null=True)),
                ('case_study_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_condition_status', models.BooleanField(default=False)),
                ('event_condition', models.CharField(blank=True, max_length=200, null=True)),
                ('event_threshold', models.FloatField(blank=True, null=True)),
                ('event_channel', models.CharField(max_length=100)),
                ('event_symbol', models.CharField(max_length=100)),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rest_api.casestudy')),
            ],
        ),
    ]
