# Generated by Django 5.2.7 on 2025-11-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='case_study_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='case_study_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='case_study_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_channel',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_condition_status',
            new_name='condition_status',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_symbol',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_threshold',
            new_name='threshold',
        ),
    ]
