# Generated by Django 5.2.7 on 2025-12-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_case_study_id_casestudy_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='user',
            new_name='email',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
