# Generated by Django 5.2.7 on 2025-12-02 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_user_casestudy_email_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudy',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/csv/files'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='driver_signal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='resample_strategy',
            field=models.CharField(default='UPPAAL', max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='uppaal_model_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/uppaal/models'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='uppaal_query',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='uppaal_query_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/uppaal/queries'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='uppaal_variables',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='user_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
