# Generated by Django 5.2.7 on 2025-12-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_casestudy_created_at_casestudy_csv_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='uppaal_variables',
            new_name='context_variables',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='main_variable',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
