# Generated by Django 5.2.7 on 2026-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_rename_uppaal_variables_casestudy_context_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='eqCondition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='htQuery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='htQueryType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='isStochastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='miQuery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='noise',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='pValue',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='plotDdtw',
            field=models.BooleanField(default=False),
        ),
    ]
