# Generated by Django 5.2.7 on 2026-02-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_casestudy_eqcondition_casestudy_htquery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='eqCondition',
            new_name='eq_condition',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='htQuery',
            new_name='ht_query',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='htQueryType',
            new_name='ht_query_type',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='isStochastic',
            new_name='is_stochastic',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='miQuery',
            new_name='mi_query',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='pValue',
            new_name='p_value',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='plotDdtw',
            new_name='plot_ddtw',
        ),
    ]
