# Generated by Django 5.2.7 on 2026-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_rename_eqcondition_casestudy_eq_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='context_variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
