# Generated by Django 5.2.7 on 2026-03-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_alter_casestudy_context_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='context_variables',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
