# Generated by Django 5.2.7 on 2026-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_casestudy_context_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='is_aggregation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
