# Generated by Django 5.2.7 on 2026-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_casestudy_is_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='n_min',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
