# Generated by Django 5.2.7 on 2026-03-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_casestudy_n_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='is_stochastic',
        ),
    ]
