# Generated by Django 5.2.7 on 2026-04-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_casestudy_final_result_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='uppaal_query',
        ),
    ]
