# Generated by Django 5.2.7 on 2026-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_remove_casestudy_uppaal_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='driver_signal',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
