# Generated by Django 5.2.7 on 2026-04-18 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_alter_casestudy_driver_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/csv/files')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='rest_api.casestudy')),
            ],
        ),
    ]
